server:
  port:8080

spring:
  jwt:
    secret-key: ${JWT_SECRET_KEY}
    access:
    expiration: 3600000 # 1시간(60분) (1000 * 60 * 60L)
    header: Authorization

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
    url: jdbc:mysql://localhost:3305/note
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true


cloud:
  aws:
    s3:
      bucket: ${BUCKET_NAME}
    stack.auto: false
    region:
      static: ap-northeast-2
    credentials:
      accessKey: ${BUCKET_ACCESS_KEY}
      secretKey: ${BUCKET_SECRET_KEY}
