server:
  port:8080

spring:
  jwt:
    secret-key: ${JWT_SECRET_KEY}
    expiration: 3600000 # 1시간(60분) (1000 * 60 * 60L)
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: ${DB_URL}
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  servlet:
    multipart:
      max-file-size: 5MB # 요청한 파일 한 개의 크기
      max-request-size: 15MB # 요청한 파일 전체의 크기
  mail:
    host: smtp.gmail.com # SMTP 서버 호스트
    port: 587 # SMTP 서버 포트
    username: ${MAIL_ID} # SMTP 서버 로그인 아이디
    password: ${MAIL_PASSWORD} # SMTP 서버 로그인 앱 패스워드
    properties:
      mail:
        smtp:
          auth: true # 사용자 인증 시도 여부 (기본값 : false)
          timeout: 5000 # Socket Read Timeout 시간(ms) (기본값 : 무한대)
          starttls:
            enable: true # StartTLS 활성화 여부 (기본값 : false)

profile:
  image:
    default: ${DEFAULT_IMAGE_URL}

cloud:
  aws:
    s3:
      bucket: ${BUCKET_NAME}
    stack.auto: false
    region:
      static: ap-northeast-2
    credentials:
      accessKey: ${BUCKET_ACCESS_KEY}
      secretKey: ${BUCKET_SECRET_KEY}
