spring:
  jwt:
    secret-key: ${JWT_SECRET_KEY}
    access:
      expiration: 3600000 # 1시간(60분) (1000 * 60 * 60L)
      header: Authorization




cloud:
  aws:
    s3:
      bucket: ${BUCKET_NAME}
    stack.auto: false
    region:
      static: ap-northeast-2
    credentials:
      accessKey: ${BUCKET_ACCESS_KEY}
      secretKey: ${BUCKET_SECRET_KEY}